[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# Test configuration
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

# RPC URLs for testing
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"
lasna = "${REACTIVE_RPC_URL}"

# Etherscan API keys
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
